/**
 * Generate a Hash from the system info to identify the user
 * @param systemInfo 
 * @returns hash string
 */
import {sha256} from 'hash-wasm';
import { SystemInfo } from './types';
export async function generateId(systemInfo:SystemInfo):Promise<string>{
 	// Generate a hash from the system info to identify the user 
	// The hash is generated by concatenating all the values of the systemInfo object and then hashing the resulting string
	const hashInput = Object.values(systemInfo).join('|');
  	return sha256(hashInput);	
}

