import { getMathFingerprint } from './helper';

/**
 * Generates and returns a mock system information object for testing.
 *
 * The returned object simulates various aspects of a system including browser details (e.g., user agent, platform, languages, timezone), 
 * device properties (e.g., screen resolution, hardware concurrency, device memory), and support for features such as cookies, local and session storage, 
 * indexedDB, WebGL, canvas, and audio. It also includes updated operating system details under the "os" property along with additional fields 
 * like plugin list, touch capabilities, vendor information, font preferences, incognito mode status, and bot detection metrics. The object also incorporates 
 * a mathematical constants fingerprint generated by {@link getMathFingerprint}.
 *
 * @returns A mock object representing system information for testing purposes.
 */

export function getMockSystemInfo() {
    const botInfo = { isBot: false, signals: [], confidence: 0.82 };
    return {
        userAgent: 'Mozilla/5.0 (Test Browser)',
        platform: 'Test Platform',
        languages: ['en-US'],
        cookiesEnabled: true,
        doNotTrack: null,
        screenResolution: [1920, 1080] as [number, number],
        colorDepth: 24,
        colorGamut: 'srgb',
        hardwareConcurrency: 8,
        deviceMemory: 8,
	os : {  os:'test', version:'T' },
        audio: null,
        localStorage: true,
        sessionStorage: true,
        indexedDB: true,
        webGL: { vendor: 'Test Vendor', renderer: 'Test Renderer' },
        canvas: { winding: false, geometry: '', text: '' },
        plugins: [],
        timezone: 'America/New_York',
        touchSupport: {
            maxTouchPoints: 0,
            touchEvent: false,
            touchStart: false
        },
        vendor: 'Test Vendor',
        vendorFlavors: ['test'],
        mathConstants: getMathFingerprint(),
        fontPreferences: { fonts: [] },
        incognito: { isPrivate: false, browserName: 'Test Browser' },
        bot: botInfo,
        confidenceScore: 0.85
    };
}

